<a href="https://colab.research.google.com/github/pandahsu849/Programing_Languages/blob/main/HW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1CQZDzhSqoIbR8JjExDr9eTq0qDzP6vQvUp9JAs4Jmic/edit?usp=sharing

In [12]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [13]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1CQZDzhSqoIbR8JjExDr9eTq0qDzP6vQvUp9JAs4Jmic/edit?usp=sharing')

In [14]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

Empty DataFrame
Columns: [日期, 時間, 分類, 品項, 金額, 付款人, 地點, 支付方式, 備註]
Index: []

In [15]:
import datetime

In [5]:
import datetime

# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))

請輸入日期 (格式：YYYY-MM-DD): 2026-03-05
請輸入時間 (格式：HH:MM): 09:20
請輸入品項: 蘿蔔糕
請輸入金額: 45

In [3]:
date_str

'2026-03-05'

In [6]:
time_str

'09:20'

In [7]:
item

'蘿蔔糕'

In [8]:
amount

45.0

In [10]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類'
    '品項': item,
    '金額': amount
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

NameError: name 'pd' is not defined

In [16]:
df

Empty DataFrame
Columns: [日期, 時間, 分類, 品項, 金額, 付款人, 地點, 支付方式, 備註]
Index: []

In [ ]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！